### ISSUE TITLE
[BUG] Icons improvement

### ISSUE THREAD

**Issue by parthasdey2304** [aayush105/aayush105#1]
Suggestion : try using skill icons api something like : 
https://skillicons.dev/icons?i=django

you will find the icon just write the name of the technology if you want to add multiple technologies in the same line write all the technologies in the query form seperated by a comma like
https://skillicons.dev/icons?i=reddit,django,flask,python,html,css

**TRY THIS**

If you liked it I have sent you connection request on LinkedIn Accept kar lena bhai🤣

**Comment by aayush105** [comment]
Ok i will look through it in free time, or are you saving you want to contribute?
Yes i have accepted your connection request.✌️@parthasdey2304

**Comment by aayush105** [comment]
> Ok i will look through it in free time, or are you saving you want to contribute?
> Yes i have accepted your connection request.✌️ @parthasdey2304

**Comment by parthasdey2304** [comment]
If you want I can contribute to it, It would take me 5 minutes to make a PR for this...

**Comment by aayush105** [comment]
> If you want I can contribute to it, It would take me 5 minutes to make a PR for this...

Thank you brother!!! @parthasdey2304

**Comment by parthasdey2304** [comment]
Glad that you liked it!
